### PR TITLE
[INTERNAL] table editor horizontal scrolling

### LINKED ISSUE #169: Can't Scroll Horizontally in Grid View with Mouse (WebStorm macOS)
Only horizontal Scrolling via Mouse or Touch Pad does not work in "Table Editor" window. Scrolling with Scroll Bars Work. Scrolling wit Mouse or Touch Pad in "Text" window works too.

WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: ide.editor.tabs.open.at.the.end=true, search.everywhere.settings=true, debugger.watches.in.variables=false
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea, com.linkedin.intellij.dust, io.probst.idea.clangformat, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.toml.lang, ru.adelf.idea.dotenv

### PR DESCRIPTION
**Pull request by SeeSharpSoft**
Fixes #169

### CODE REVIEW

File: src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java [hunk 1]
```diff
@@ -27,7 +27,7 @@ public void testZoomOnCsvTable() {
         assertEquals(size + 1, new_size);
     }
 
-    public void testScrollOnCsvTable() {
+    public void testScrollVerticallyOnCsvTable() {
```
Comment (SeeSharpSoft) [inline src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java]:
```suggestion
    public void testVerticalScrollingOnCsvTable() {
```

File: src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java [hunk 2]
```diff
@@ -37,12 +37,39 @@ public void testScrollOnCsvTable() {
...
+        hScrollValue = fileEditor.getTableScrollPane().getVerticalScrollBar().getValue();
+        vScrollValue = fileEditor.getTableScrollPane().getHorizontalScrollBar().getValue();
 
         // 90 is max in this case
-        assertEquals(90, scrollValue);
+        assertEquals(90, hScrollValue);
+        assertEquals(0, vScrollValue);
+    }
+
+    public void testScrollHorizontalOnCsvTable() {
```
Comment (SeeSharpSoft) [inline src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java]:
```suggestion
    public void testHorizontalScrollingOnCsvTable() {
```
